# Generated by Django 6.0.5 on 2026-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
