# Generated by Django 6.0.5 on 2026-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='plan',
            name='beneficios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='orden',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
