# Generated by Django 6.0.5 on 2026-05-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoia',
            name='estado_imagen',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesando', 'Procesando'), ('Completado', 'Completado'), ('Error', 'Error')], default='Pendiente', max_length=30),
        ),
    ]
