# Generated by Django 6.0.5 on 2026-06-30 00:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_telefono_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.nombre_imagen_usuario),
        ),
    ]
