# Generated by Django 6.0.5 on 2026-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autenticacion',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('GOOGLE', 'Google')], default='LOCAL', max_length=10),
        ),
    ]
