# Generated by Django 6.0.5 on 2026-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plan_alter_diagnosticoia_planta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticoia',
            old_name='como_prevenir',
            new_name='prevencion',
        ),
        migrations.RenameField(
            model_name='diagnosticoia',
            old_name='tratamiento',
            new_name='tratamiento_natural',
        ),
        migrations.AddField(
            model_name='diagnosticoia',
            name='tratamiento_quimico',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
