# Generated by Django 6.0.5 on 2026-06-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_autenticacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='estado',
            new_name='state',
        ),
    ]
