# Generated by Django 6.0.5 on 2026-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_telefono_usuario_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
