# Generated by Django 6.0.5 on 2026-07-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chat_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoia',
            name='lesiones_detectadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de lesiones detectadas por AgroVisionAI.'),
        ),
    ]
