# Generated by Django 6.0.5 on 2026-07-15 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_diagnosticoia_lesiones_detectadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='precio',
        ),
        migrations.CreateModel(
            name='PlanPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20)),
                ('comprobante', models.FileField(upload_to='comprobantes/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_plan', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_plan', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plan_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_desde', to='api.plan')),
                ('plan_solicitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_hacia', to='api.planprecio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
