# Generated by Django 6.0.5 on 2026-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_plan_precio_planprecio_solicitudcambioplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoia',
            name='progreso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
