"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# ==============================
# CARGAR VARIABLES DE ENTORNO
# ==============================
import environ
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()


# ==============================
# CONFIGURACIÓN 
# ==============================

# DETERMINAMOS EL ENTORNO
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")

# CARGAMOS ARCHIVOS .env SEGÚN EL ENTORNO
if ENVIRONMENT == "production":
    env.read_env(BASE_DIR / ".env.env")
else:
    env.read_env(BASE_DIR / ".env")

# INDICAMOS SI ESTAMOS EN PRODUCCIÓN
IS_PRODUCTION = ENVIRONMENT == "production"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!xqg$2q$rl-o=c+!+4g@58tm=d^_cgc!qhu^!++4rg+9na^s*n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False, cast=bool)

# ALLOWED_HOSTS
ALLOWED_HOSTS = env(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1"
).split(",")

# URLS
SITE_URL = env("SITE_URL", default="http://localhost:8000")

# SERVICIOS
GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default=None)
OPENAI_API_KEY = env("OPENAI_API_KEY", default=None)
GEMINI_API_KEY = env("GEMINI_API_KEY", default=None)

# OTP EMAIL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = env("EMAIL_HOST", default=None)
EMAIL_PORT = int(env("EMAIL_PORT", default=587))
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default="True") == "True"

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default=None)
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default=None)

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=None)

# Application definition
INSTALLED_APPS = [
    'api',
    "django_crontab",
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#
CRONJOBS = [
    ('* * * * *', 'api.cron.verificar_planes'),
]

#
AUTH_USER_MODEL = 'api.Usuario'

#
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
    #permitir: AllowAny
    #bloquear: IsAuthenticated
}


# -------------------
# Cookies y sesiones
# -------------------
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_AGE = 21600          # 6horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

SESSION_COOKIE_PATH = '/'
CSRF_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None

SESSION_COOKIE_HTTPONLY = True

SESSION_SAVE_EVERY_REQUEST = True

#CORS
CORS_ALLOW_CREDENTIALS = True

# Google
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

# ARCHIVOS
MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS
CORS_ALLOWED_ORIGINS = env(
    "CORS_ALLOWED_ORIGINS",
    default=""
).split(",")

CSRF_TRUSTED_ORIGINS = env(
    "CSRF_TRUSTED_ORIGINS",
    default=""
).split(",")

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / env(
            'SQLITE_DB_PATH',
            default='db.sqlite3'
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'